Test new rsvg

diff --git a/mingw-w64-librsvg/PKGBUILD b/mingw-w64-librsvg/PKGBUILD
--- a/mingw-w64-librsvg/PKGBUILD
+++ b/mingw-w64-librsvg/PKGBUILD
@@ -3,92 +3,101 @@
 _realname=librsvg
 pkgbase=mingw-w64-${_realname}
 pkgname=("${MINGW_PACKAGE_PREFIX}-${_realname}")
-pkgver=2.57.0
+pkgver=2.61.0
 pkgrel=1
 pkgdesc="SVG rendering library (mingw-w64)"
 arch=('any')
-mingw_arch=('mingw32' 'mingw64' 'ucrt64' 'clang64' 'clang32' 'clangarm64')
+mingw_arch=('mingw32' 'mingw64' 'ucrt64' 'clang64' 'clangarm64')
 url="https://wiki.gnome.org/Projects/LibRsvg"
+msys2_references=(
+  "cpe: cpe:/a:gnome:librsvg"
+  "purl: pkg:cargo/librsvg"
+)
 license=("spdx:LGPL-2.1-or-later")
-makedepends=("${MINGW_PACKAGE_PREFIX}-autotools"
+makedepends=("${MINGW_PACKAGE_PREFIX}-meson"
+             "${MINGW_PACKAGE_PREFIX}-ninja"
+             "${MINGW_PACKAGE_PREFIX}-gobject-introspection"
              "${MINGW_PACKAGE_PREFIX}-vala"
              "${MINGW_PACKAGE_PREFIX}-rust"
+             "${MINGW_PACKAGE_PREFIX}-cargo-c"
+             "${MINGW_PACKAGE_PREFIX}-gi-docgen"
+             "${MINGW_PACKAGE_PREFIX}-python-docutils"
              "${MINGW_PACKAGE_PREFIX}-cc")
 depends=("${MINGW_PACKAGE_PREFIX}-gdk-pixbuf2"
          "${MINGW_PACKAGE_PREFIX}-pango"
          "${MINGW_PACKAGE_PREFIX}-cairo"
          "${MINGW_PACKAGE_PREFIX}-libxml2")
-options=('staticlibs' 'strip')
+optdepends=("${MINGW_PACKAGE_PREFIX}-gtk3: for rsvg-view-3")
 source=("https://download.gnome.org/sources/librsvg/${pkgver%.*}/${_realname}-${pkgver}.tar.xz"
-        "0001-configure-set-pass-prefix-to-pkg-config-when-retriev.patch"
-        "glib-0.18.1.tar.gz::https://crates.io/api/v1/crates/glib/0.18.1/download"
-        "glib-rs.patch")
-sha256sums=('335fe2e0c2cbf1b7bf0668651224a23e135451f0b1793cd813649be2bffa74e8'
-            '189eec6486c9ef6cf1071af9750405bc41e16ae3a55ad663435e574369fec915'
-            'SKIP'
-            'SKIP')
+        "0004-add-option-for-disabling-convert.patch")
+sha256sums=('dbd0db40a1179a382fbb8cc930837671b973d722ba106a3dee2aad0fd858e2c4'
+            '0e042886d313b37f5db5e0405a5e37b3d3e4a6c66f94186677406136fa0e7a17')
 msys2_repository_url="https://gitlab.gnome.org/GNOME/librsvg"
+noextract=("${_realname}-${pkgver}.tar.xz")
 
 prepare() {
-  # Patch the glib rust bindings first
-  cd "${srcdir}/glib-0.18.1"
-  patch -p1 -i "${srcdir}/glib-rs.patch"
+  bsdtar -xf "${_realname}-${pkgver}.tar.xz" 2>/dev/null || true
 
-  cd "${srcdir}/${_realname}-${pkgver}"
-  patch -p1 -i "${srcdir}/0001-configure-set-pass-prefix-to-pkg-config-when-retriev.patch"
+  cd "${_realname}-${pkgver}"
 
-
-  ## Jeroen: try to fix static linking of rust to glib
-  ## See: https://github.com/msys2/MINGW-packages/issues/18574
-  echo "" >> Cargo.toml
-  echo "[patch.crates-io]" >> Cargo.toml
-  echo "glib = { path = '../glib-0.18.1' }" >> Cargo.toml
-
-  cargo update --package glib
+  # fails to link for the static build, so skip for now
+  patch -p1 -i "${srcdir}/0004-add-option-for-disabling-convert.patch"
+  cargo --version
   cargo fetch --locked
 }
 
 build() {
-  [[ -d "${srcdir}/build-${MSYSTEM}" ]] && rm -rf "${srcdir}/build-${MSYSTEM}"
-  mkdir "${srcdir}/build-${MSYSTEM}" && cd "${srcdir}/build-${MSYSTEM}"
-
-  # html documentation doesn't install from out of tree
-  cp -rf "${srcdir}/${_realname}-${pkgver}/doc" "${srcdir}/build-${MSYSTEM}/doc"
-
   # https://github.com/msys2/MINGW-packages/pull/13622#issuecomment-1285820970
   export WINAPI_NO_BUNDLED_LIBRARIES=1
 
-  export lt_cv_deplibs_check_method='pass_all'
+  MSYS2_ARG_CONV_EXCL="--prefix=" \
+    meson setup \
+      --prefix="${MINGW_PREFIX}" \
+      --wrap-mode=nodownload \
+      --auto-features=enabled \
+      --default-library=static \
+      --buildtype=plain \
+      -Dintrospection=disabled \
+      -Davif=disabled \
+      -Dtests=false \
+      -Ddocs=disabled \
+      -Dpixbuf-loader=disabled \
+      -Drsvg-convert=disabled \
+      "build-${MSYSTEM}-static" \
+      "${_realname}-${pkgver}"
 
-  # an argument passed to glib-mkenums starts with a c++ comment
-  export MSYS2_ARG_CONV_EXCL="/*"
-  # so the unix path gets preserved when passed through pkg-config
-  MSYS2_ARG_CONV_EXCL="$MSYS2_ARG_CONV_EXCL;--define-variable=prefix"
+  meson compile -C "build-${MSYSTEM}-static"
 
+  MSYS2_ARG_CONV_EXCL="--prefix=" \
+    meson setup \
+      --prefix="${MINGW_PREFIX}" \
+      --wrap-mode=nodownload \
+      --auto-features=enabled \
+      --buildtype=plain \
+      -Davif=disabled \
+      "build-${MSYSTEM}" \
+      "${_realname}-${pkgver}"
 
-  # Hack hack
-  cp -fv ${MINGW_PREFIX}/lib/gcc/${MINGW_CHOST}/12.2.0/libgcc.a ${MINGW_PREFIX}/lib/gcc/${MINGW_CHOST}/12.2.0/libgcc_eh.a || true
-
-  # Autoconf thinks we need pangoft2, but it is not needed.
-  cp -fv ${MINGW_PREFIX}/lib/pkgconfig/pango.pc ${MINGW_PREFIX}/lib/pkgconfig/pangoft2.pc
-
-  ../${_realname}-${pkgver}/configure \
-    --prefix=${MINGW_PREFIX} \
-    --build=${MINGW_CHOST} \
-    --host=${MINGW_CHOST} \
-    --enable-static \
-    --enable-shared \
-    --disable-introspection \
-    --enable-tools=yes \
-    --enable-pixbuf-loader=yes \
-    --enable-gtk-doc=no \
-    --enable-gtk-doc-html=no \
-    --enable-silent-rules
-
-  make
+  meson compile -C "build-${MSYSTEM}"
 }
 
-package() {
-  make -C "${srcdir}/build-${MSYSTEM}" DESTDIR="${pkgdir}" install
+package_librsvg() {
+  conflicts=("${MINGW_PACKAGE_PREFIX}-${_realname}-2.40")
+  replaces=("${MINGW_PACKAGE_PREFIX}-${_realname}-2.40")
+
+  meson install -C "build-${MSYSTEM}-static" --destdir "${pkgdir}"
+  meson install -C "build-${MSYSTEM}" --destdir "${pkgdir}"
+
   install -Dm644 "${srcdir}/${_realname}-${pkgver}/COPYING.LIB" "${pkgdir}${MINGW_PREFIX}/share/licenses/${_realname}/COPYING.LIB"
 }
+
+# template start; name=mingw-w64-splitpkg-wrappers; version=1.0;
+# vim: set ft=bash :
+
+# generate wrappers
+for _name in "${pkgname[@]}"; do
+  _short="package_${_name#${MINGW_PACKAGE_PREFIX}-}"
+  _func="$(declare -f "${_short}")"
+  eval "${_func/#${_short}/package_${_name}}"
+done
+# template end;
